#!/usr/bin/sh

# Startup
sxhkd &
xfce4-power-manager &
light-locker &
polybar example &
setxkbmap -layout us -variant dvorak-intl -option altwin:prtsc_rwin, caps:escape, ctrl:swap_lalt_lctl, shift:both_capslock_cancel &
nm-applet &
blueberry-tray &
xset b off &

#Init desktops
~/dotfiles/scripts/monitor/init.sh

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop=8 state=floating follow=on
bspc rule -a Firefox desktop=1
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
