[theme]
name="plain"
[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"
[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"
